# Generated by Django 4.1 on 2022-09-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antioxidante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energetico', models.CharField(help_text='ejemplo 150 Kcal', max_length=100)),
                ('vd_energetico', models.IntegerField(help_text='%')),
                ('carbohidratos', models.CharField(help_text='1g', max_length=100)),
                ('vd_carbohidratos', models.IntegerField(help_text='%')),
                ('grasas', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas', models.IntegerField(help_text='%')),
                ('grasas_saturadas', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas_saturadas', models.IntegerField(help_text='%')),
                ('proteinas', models.CharField(help_text='1g', max_length=100)),
                ('vd_proteinas', models.IntegerField(help_text='%')),
                ('grasas_trans', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas_trans', models.IntegerField(help_text='%')),
                ('fibra', models.CharField(help_text='1g', max_length=100)),
                ('vd_fibra', models.IntegerField(help_text='%')),
                ('sodio', models.CharField(help_text='500mg', max_length=100)),
                ('vd_sodio', models.IntegerField(help_text='%')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
                ('porcion', models.IntegerField(blank=True, help_text='numerico g por unidad', null=True)),
                ('destacado', models.BooleanField(blank=True, default=True, null=True)),
                ('galery', models.TextField(blank=True)),
                ('antioxidante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.antioxidante')),
                ('conservador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.conservador')),
                ('estabilizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.estabilizante')),
                ('ingredientes', models.ManyToManyField(blank=True, null=True, related_name='product', to='products.ingrediente')),
                ('valores_nutricionales', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.valores')),
            ],
        ),
    ]
