# Generated by Django 4.1 on 2022-09-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categorias', related_query_name='sub_categorias', to='products.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('nombre_es', models.CharField(max_length=500, null=True, unique=True)),
                ('nombre_en', models.CharField(max_length=500, null=True, unique=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True, unique=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True, unique=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('miniatura', models.ImageField(upload_to='')),
                ('destacado', models.BooleanField(default=True)),
                ('porcion', models.IntegerField(blank=True, help_text='numerico g por unidad', null=True)),
                ('descripcion', models.TextField()),
                ('descripcion_es', models.TextField(null=True)),
                ('descripcion_en', models.TextField(null=True)),
                ('descripcion_ru', models.TextField(null=True)),
                ('descripcion_zh_hans', models.TextField(null=True)),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='products.categoriasub')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ValoresNutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energetico', models.CharField(help_text='ejemplo 150 Kcal', max_length=100)),
                ('vd_energetico', models.IntegerField(help_text='%')),
                ('carbohidratos', models.CharField(help_text='1g', max_length=100)),
                ('vd_carbohidratos', models.IntegerField(help_text='%')),
                ('proteinas', models.CharField(help_text='1g', max_length=100)),
                ('vd_proteinas', models.IntegerField(help_text='%')),
                ('grasas', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas', models.IntegerField(help_text='%')),
                ('grasas_saturadas', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas_saturadas', models.IntegerField(help_text='%')),
                ('grasas_trans', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas_trans', models.IntegerField(help_text='%')),
                ('fibra', models.CharField(help_text='1g', max_length=100)),
                ('vd_fibra', models.IntegerField(help_text='%')),
                ('sodio', models.CharField(help_text='500mg', max_length=100)),
                ('vd_sodio', models.IntegerField(help_text='%')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_nutricionales', related_query_name='valores_nutricionales', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', related_query_name='galeria', to='products.product')),
            ],
        ),
    ]
