# Generated by Django 4.1 on 2022-09-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='antioxidante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.antioxidante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='conservador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.conservador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='estabilizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.estabilizante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galery',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='products.ingrediente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='porcion',
            field=models.IntegerField(blank=True, help_text='numerico g por unidad', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='valores_nutricionales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.valores'),
        ),
    ]
