# Generated by Django 4.1 on 2022-09-18 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_categoria',
            field=models.ForeignKey(help_text='Busqueda por Categoria superior', on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='products.categoriasub'),
        ),
    ]
