# Generated by Django 3.2.16 on 2022-12-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidad',
            field=models.CharField(blank=True, help_text='unidad de porcion: kg, caja, gr (3 chorizos)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='porcion',
            field=models.IntegerField(blank=True, help_text='cantidad', null=True),
        ),
    ]
