# Generated by Django 4.1 on 2022-09-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='antioxidante',
        ),
        migrations.RemoveField(
            model_name='product',
            name='conservante',
        ),
        migrations.RemoveField(
            model_name='product',
            name='estabilizante',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descripcion_zh_hans',
            field=models.TextField(null=True),
        ),
    ]
