# Generated by Django 4.1 on 2022-09-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='valores_nutricionales',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valores',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=True),
        ),
    ]
