# Generated by Django 4.1 on 2022-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_valores_nutricionales_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='galery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
