# Generated by Django 4.1 on 2022-09-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_antioxidante_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Antioxidante',
        ),
        migrations.DeleteModel(
            name='Conservador',
        ),
        migrations.DeleteModel(
            name='Estabilizante',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
