# Generated by Django 4.1 on 2022-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sub_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_en',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_es',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_ru',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_zh_hans',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriasub',
            name='nombre_en',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriasub',
            name='nombre_es',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriasub',
            name='nombre_ru',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriasub',
            name='nombre_zh_hans',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
