# Generated by Django 3.2.19 on 2023-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='desktop',
            field=models.ImageField(help_text='845px de alto  // 1920px de ancho', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='movil',
            field=models.ImageField(help_text='360px de alto // 360px de ancho', upload_to=''),
        ),
    ]
