# Generated by Django 4.1 on 2022-09-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_galery_alter_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresNutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energetico', models.CharField(help_text='ejemplo 150 Kcal', max_length=100)),
                ('vd_energetico', models.IntegerField(help_text='%')),
                ('carbohidratos', models.CharField(help_text='1g', max_length=100)),
                ('vd_carbohidratos', models.IntegerField(help_text='%')),
                ('grasas', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas', models.IntegerField(help_text='%')),
                ('grasas_saturadas', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas_saturadas', models.IntegerField(help_text='%')),
                ('proteinas', models.CharField(help_text='1g', max_length=100)),
                ('vd_proteinas', models.IntegerField(help_text='%')),
                ('grasas_trans', models.CharField(help_text='1g', max_length=100)),
                ('vd_grasas_trans', models.IntegerField(help_text='%')),
                ('fibra', models.CharField(help_text='1g', max_length=100)),
                ('vd_fibra', models.IntegerField(help_text='%')),
                ('sodio', models.CharField(help_text='500mg', max_length=100)),
                ('vd_sodio', models.IntegerField(help_text='%')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_nutricionales', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
    ]
