# Generated by Django 4.1.4 on 2023-07-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230703_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeBanner',
        ),
    ]
