# Generated by Django 4.1 on 2022-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_thumbnail_product_galeria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
