# Generated by Django 4.1.4 on 2023-07-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='productos/galeria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='miniatura',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
