# Generated by Django 4.1.4 on 2023-08-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_galeria_imagen_alter_product_miniatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='miniatura',
            field=models.ImageField(upload_to=''),
        ),
    ]
