# Generated by Django 4.1 on 2022-09-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_nombre_alter_product_nombre_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='url',
        ),
    ]
