# Generated by Django 4.1 on 2022-09-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_antioxidante_alter_product_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ingrediente'),
        ),
    ]
