# Generated by Django 4.1 on 2022-09-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_galeria_product_miniatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasub',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categorias', related_query_name='sub_categorias', to='products.categoria'),
        ),
    ]
