# Generated by Django 4.1 on 2022-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento CEO', max_length=500, null=True),
        ),
    ]
