# Generated by Django 4.1 on 2022-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_categoriasub_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriasub',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
