# Generated by Django 4.1 on 2022-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_galeria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
    ]
