# Generated by Django 4.1 on 2022-09-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_galeria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='conservador',
            new_name='conservante',
        ),
    ]
