# Generated by Django 4.1 on 2022-09-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_conservador_product_conservante'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_es',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_ru',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_zh_hans',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
    ]
