# Generated by Django 4.1 on 2022-09-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
                ('descripcion', models.TextField()),
                ('descripcion_es', models.TextField(null=True)),
                ('descripcion_en', models.TextField(null=True)),
                ('descripcion_ru', models.TextField(null=True)),
                ('descripcion_zh_hans', models.TextField(null=True)),
                ('galeria', models.TextField()),
                ('personas', models.IntegerField(default=1)),
                ('productos_sugeridos', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparacion', to='receta.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='receta.receta')),
            ],
        ),
    ]
