# Generated by Django 4.1 on 2022-10-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('nombre_es', models.CharField(max_length=500, null=True)),
                ('nombre_en', models.CharField(max_length=500, null=True)),
                ('nombre_ru', models.CharField(max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('miniatura', models.ImageField(upload_to='')),
                ('tiempo_preparacion', models.CharField(max_length=500)),
                ('porcion_personas', models.IntegerField(default=1)),
                ('descripcion', models.TextField()),
                ('descripcion_es', models.TextField(null=True)),
                ('descripcion_en', models.TextField(null=True)),
                ('descripcion_ru', models.TextField(null=True)),
                ('descripcion_zh_hans', models.TextField(null=True)),
                ('ingredientes', models.TextField()),
                ('ingredientes_es', models.TextField(null=True)),
                ('ingredientes_en', models.TextField(null=True)),
                ('ingredientes_ru', models.TextField(null=True)),
                ('ingredientes_zh_hans', models.TextField(null=True)),
                ('preparacion', models.TextField()),
                ('preparacion_es', models.TextField(null=True)),
                ('preparacion_en', models.TextField(null=True)),
                ('preparacion_ru', models.TextField(null=True)),
                ('preparacion_zh_hans', models.TextField(null=True)),
                ('productos_sugeridos', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='receta.receta')),
            ],
        ),
    ]
