# Generated by Django 4.1 on 2022-09-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
