# Generated by Django 4.1 on 2022-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_delete_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='galeria',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
