# Generated by Django 4.1 on 2022-09-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_galeria_remove_preparacion_receta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
