# Generated by Django 4.1 on 2022-09-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0002_remove_receta_ingredientes_remove_receta_preparacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_es',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_ru',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_zh_hans',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='nombre_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='nombre_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='nombre_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='nombre_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='nombre_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='nombre_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='nombre_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='nombre_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='descripcion_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='descripcion_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombre_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombre_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombre_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='nombre_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
