# Generated by Django 4.1 on 2022-09-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0003_receta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='miniatura',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
