# Generated by Django 4.1 on 2022-09-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0003_receta_galeria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='galeria',
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='receta.receta')),
            ],
        ),
    ]
