# Generated by Django 4.1 on 2022-09-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0004_receta_miniatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
