# Generated by Django 4.1 on 2022-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0004_remove_receta_galeria_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='galeria',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
