# Generated by Django 4.1.4 on 2023-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('desktop', models.ImageField(help_text='845px de alto  // 1920px de ancho', upload_to='')),
                ('movil', models.ImageField(help_text='360px de alto // 360px de ancho', upload_to='')),
            ],
        ),
    ]
