# Generated by Django 4.1.4 on 2023-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='desktop',
            field=models.ImageField(help_text='845px de alto  // 1920px de ancho', upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='movil',
            field=models.ImageField(help_text='360px de alto // 360px de ancho', upload_to='banners'),
        ),
    ]
