# Generated by Django 4.1.4 on 2023-08-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_homebanner_desktop_alter_homebanner_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='text_cont_img',
            field=models.ImageField(default='', upload_to='banners'),
            preserve_default=False,
        ),
    ]
