# Generated by Django 4.1 on 2022-09-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrucosYConsejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('titulo_es', models.CharField(max_length=255, null=True)),
                ('titulo_en', models.CharField(max_length=255, null=True)),
                ('titulo_ru', models.CharField(max_length=255, null=True)),
                ('titulo_zh_hans', models.CharField(max_length=255, null=True)),
                ('video', models.URLField(blank=True, help_text='si este campo no esta vacío, las imágenes agregadas no serán usadas', null=True)),
                ('contenido', models.TextField()),
                ('contenido_es', models.TextField(null=True)),
                ('contenido_en', models.TextField(null=True)),
                ('contenido_ru', models.TextField(null=True)),
                ('contenido_zh_hans', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True)),
                ('nombre_es', models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True)),
                ('nombre_en', models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True)),
                ('nombre_ru', models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True)),
                ('nombre_zh_hans', models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='blog.trucosyconsejos')),
            ],
        ),
    ]
