# Generated by Django 4.1 on 2022-09-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_es',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_ru',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='nombre_zh_hans',
            field=models.CharField(blank=True, help_text='ayuda al posicionamiento SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='contenido_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='contenido_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='contenido_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='contenido_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='titulo_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='titulo_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='titulo_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='titulo_zh_hans',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
