# Generated by Django 4.1 on 2022-09-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='nombre_en',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='nombre_es',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='nombre_ru',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='nombre_zh_hans',
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trucosyconsejos',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='trucosyconsejos',
            name='titulo_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trucosyconsejos',
            name='titulo_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trucosyconsejos',
            name='titulo_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trucosyconsejos',
            name='titulo_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
