# Generated by Django 4.1 on 2022-09-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_galeria_nombre_remove_galeria_nombre_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucosyconsejos',
            name='miniatura',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
