# Generated by Django 4.1.4 on 2023-07-28 21:03

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_es', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_en', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_zh_hans', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('text_es', models.TextField(blank=True, max_length=500, null=True)),
                ('text_en', models.TextField(blank=True, max_length=500, null=True)),
                ('text_ru', models.TextField(blank=True, max_length=500, null=True)),
                ('text_zh_hans', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_es', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_en', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_zh_hans', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_es', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_zh_hans', models.TextField(blank=True, null=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion', to='pages.pagina')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_es', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_en', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_zh_hans', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_es', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_zh_hans', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=pages.models.upload_path)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='pages.seccion')),
            ],
        ),
    ]
