# Generated by Django 4.1.4 on 2023-07-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pagina_text_alter_pagina_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='posicion',
        ),
    ]
