# Generated by Django 4.1 on 2022-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='tag',
            field=models.ManyToManyField(to='posts.tag'),
        ),
        migrations.AddField(
            model_name='trucosyconsejos',
            name='tag',
            field=models.ManyToManyField(to='posts.tag'),
        ),
    ]
