# Generated by Django 4.1 on 2022-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_novedades_tag_trucosyconsejos_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='contenido_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='contenido_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='contenido_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='contenido_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='titulo_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='titulo_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='titulo_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='titulo_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='nombre_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='nombre_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='nombre_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='nombre_zh_hans',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
