# Generated by Django 4.1 on 2022-10-16 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_novedades_publicar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='publicar',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='trucosyconsejos',
            name='publicar',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='fecha de publicacion'),
        ),
    ]
